# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: home
    url: '#home'
    weight: 10
  - name: Publications
    url: 'publication'
    weight: 20
  - name: Teaching
    identifier: teaching
  #  url: 'teaching'
    weight: 30
  - name: DCC 129 - FTC (2024/1)
    identifier: ftc
    url: 'teaching/ftc'
    parent: teaching
    weight: 10
  - name: DCC 831/030/049 - Info. Theory (2024/1)
    identifier: info-theory
    url: 'teaching/info-theory'
    parent: teaching
    weight: 20
  - name: DCC 836 - ILC (2022/1)
    identifier: ilc
    url: 'teaching/ilc'
    parent: teaching
    weight: 30
  - name: DCC 831/030/049 - QIF (2022/3)
    identifier: qif
    url: 'teaching/qif'
    parent: teaching
    weight: 40
  - name: FAQ - Teaching & Grading
    identifier: faq-teaching-grading-1
    url: 'faqs/teaching-grading'
    parent: teaching
    weight: 50
  - name: Awards and honors
    identifier: awards
    url: 'awards'
    weight: 40
  - name: About
    identifier: about
  #  url: 'about'
    weight: 50
  - name: A little more about myself
    identifier: about-more
    url: 'about'
    parent: about
    weight: 10
  - name: FAQ - Research & Science
    identifier: faq-research-science
    url: 'faqs/research-science'
    parent: about
    weight: 20
  - name: FAQ - Teaching & Grading
    identifier: faq-teaching-grading-2
    url: 'faqs/teaching-grading'
    parent: about
    weight: 30
  # - name: Contact
  #   url: '#contact'
  #   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
